import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  title: { fontSize: 18, fontWeight: "bold", marginBottom: 20, textAlign: "center" },
  section: { marginBottom: 16 },
  heading: { fontSize: 14, fontWeight: "bold", marginBottom: 8, borderBottomWidth: 1, paddingBottom: 4 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 120, fontWeight: "bold" },
  value: { flex: 1 },
  table: { marginTop: 8 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f0f0f0", padding: 4, fontWeight: "bold" },
  tableRow: { flexDirection: "row", padding: 4, borderBottomWidth: 0.5 },
  colDate: { width: "12%" },
  colOdometer: { width: "15%" },
  colKm: { width: "8%" },
  colFrom: { width: "20%" },
  colTo: { width: "20%" },
  colPurpose: { flex: 1 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "gray", textAlign: "center" },
});

interface PdfReportProps {
  userName: string;
  taxYear: number;
  vehicleName: string;
  licensePlate: string;
  openingOdometer: number | null;
  closingOdometer: number | null;
  totalKm: number;
  businessKm: number;
  businessPercent: number;
  deductibleAmount: number;
  trips: Array<{
    date: string;
    startOdometer: number;
    endOdometer: number;
    totalKm: number;
    startLocation: string;
    endLocation: string;
    purpose: string;
  }>;
}

export function SarsPdfReport({
  userName, taxYear, vehicleName, licensePlate, openingOdometer, closingOdometer,
  totalKm, businessKm, businessPercent, deductibleAmount, trips,
}: PdfReportProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>SARS Travel Logbook</Text>

        <View style={styles.section}>
          <Text style={styles.heading}>Taxpayer Details</Text>
          <View style={styles.row}><Text style={styles.label}>Name:</Text><Text style={styles.value}>{userName}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Tax Year:</Text><Text style={styles.value}>{taxYear}/{taxYear + 1}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Vehicle Details</Text>
          <View style={styles.row}><Text style={styles.label}>Vehicle:</Text><Text style={styles.value}>{vehicleName}</Text></View>
          <View style={styles.row}><Text style={styles.label}>License Plate:</Text><Text style={styles.value}>{licensePlate}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Opening (1 Mar):</Text><Text style={styles.value}>{openingOdometer?.toLocaleString() || "—"} km</Text></View>
          <View style={styles.row}><Text style={styles.label}>Closing (28 Feb):</Text><Text style={styles.value}>{closingOdometer?.toLocaleString() || "—"} km</Text></View>
          <View style={styles.row}><Text style={styles.label}>Total Kilometres:</Text><Text style={styles.value}>{totalKm.toLocaleString()} km</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Summary</Text>
          <View style={styles.row}><Text style={styles.label}>Business Kilometres:</Text><Text style={styles.value}>{businessKm.toLocaleString()} km</Text></View>
          <View style={styles.row}><Text style={styles.label}>Business Use:</Text><Text style={styles.value}>{businessPercent}%</Text></View>
          <View style={styles.row}><Text style={styles.label}>Estimated Deduction:</Text><Text style={styles.value}>R {deductibleAmount.toLocaleString()}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Business Trips</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={styles.colDate}>Date</Text>
              <Text style={styles.colOdometer}>Start/End</Text>
              <Text style={styles.colKm}>Km</Text>
              <Text style={styles.colFrom}>From</Text>
              <Text style={styles.colTo}>To</Text>
              <Text style={styles.colPurpose}>Purpose</Text>
            </View>
            {trips.map((t, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={styles.colDate}>{t.date}</Text>
                <Text style={styles.colOdometer}>{t.startOdometer}-{t.endOdometer}</Text>
                <Text style={styles.colKm}>{t.totalKm}</Text>
                <Text style={styles.colFrom}>{t.startLocation}</Text>
                <Text style={styles.colTo}>{t.endLocation}</Text>
                <Text style={styles.colPurpose}>{t.purpose}</Text>
              </View>
            ))}
          </View>
        </View>

        <Text style={styles.footer}>
          This logbook was generated by TravelTrack. You must retain this record for at least 5 years from the date of submission of your tax return as it may be required for verification by SARS.
        </Text>
      </Page>
    </Document>
  );
}
